//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGlovePrototype2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOGService")]
    public interface IOGService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOGService/GetMappings", ReplyAction="http://tempuri.org/IOGService/GetMappingsResponse")]
        int[] GetMappings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOGService/GetMappings", ReplyAction="http://tempuri.org/IOGService/GetMappingsResponse")]
        System.Threading.Tasks.Task<int[]> GetMappingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOGService/GetCore", ReplyAction="http://tempuri.org/IOGService/GetCoreResponse")]
        OpenGlove.OpenGloveSDKCore GetCore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOGService/GetCore", ReplyAction="http://tempuri.org/IOGService/GetCoreResponse")]
        System.Threading.Tasks.Task<OpenGlove.OpenGloveSDKCore> GetCoreAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOGServiceChannel : OpenGlovePrototype2.ServiceReference1.IOGService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OGServiceClient : System.ServiceModel.ClientBase<OpenGlovePrototype2.ServiceReference1.IOGService>, OpenGlovePrototype2.ServiceReference1.IOGService {
        
        public OGServiceClient() {
        }
        
        public OGServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OGServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OGServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OGServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetMappings() {
            return base.Channel.GetMappings();
        }
        
        public System.Threading.Tasks.Task<int[]> GetMappingsAsync() {
            return base.Channel.GetMappingsAsync();
        }
        
        public OpenGlove.OpenGloveSDKCore GetCore() {
            return base.Channel.GetCore();
        }
        
        public System.Threading.Tasks.Task<OpenGlove.OpenGloveSDKCore> GetCoreAsync() {
            return base.Channel.GetCoreAsync();
        }
    }
}
